name: Deploy DocC

on:
  push:
  release:
    types:
      - published
      
permissions:
  contents: write
  
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build_docs:
    
    runs-on: macos-latest
    
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build DocC
        run: |
          swift package update;
          
          DERIVED_DATA_PATH=.build/docbuild
          
          PROJECT_NAME='mew-wallet-ios-secp256k1'
          DESTINATION='platform=iOS Simulator,name=iPhone 13 Pro Max'
          
          swift package dump-pif > /dev/null || true
          xcodebuild clean -scheme $PROJECT_NAME -destination $DESTINATION > /dev/null || true
          
          xcodebuild docbuild \
           -scheme $PROJECT_NAME \
           -destination $DESTINATION \
           -configuration Release \
           -derivedDataPath $DERIVED_DATA_PATH
           
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting $DERIVED_DATA_PATH/Build/Products/Debug-iphoneos/mew-wallet-ios-secp256k1.doccarchive \
            --hosting-base-path mew-wallet-ios-secp256k1 \
            --output-path docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
